#!/bin/sh
export PYTHONPATH=$PWD:$PYTHONPATH
if python3.5 -V >/dev/null 2>&1; then
	exec python3.5 -m "sshuttle" "$@"
elif python2.7 -V >/dev/null 2>&1; then
	exec python2.7 -m "sshuttle" "$@"
else
	exec python -m "sshuttle" "$@"
fi
