[tox]
downloadcache = {toxworkdir}/cache/
envlist =
    py310,
    py311,
    py312,

[testenv]
basepython =
    py310: python3.10
    py311: python3.11
    py312: python3.12
commands =
    pip install -e .
    # actual flake8 test
    flake8 sshuttle tests
    # flake8 complexity warnings
    flake8 sshuttle tests --exit-zero --max-complexity=10
    pytest
deps =
    -rrequirements-tests.txt
